name: Trigger Cloud Build

on:
  workflow_run:
    workflows: ["Compile Check"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.AGM_HUB_SERVICE_ACCOUNT_KEY }}'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Build and deploy using repository configuration
        run: |
          gcloud builds submit . \
            --config=cloudbuild.yaml \
            --project=agm-datalake \
            --service-account=projects/agm-datalake/serviceAccounts/agm-hub@agm-datalake.iam.gserviceaccount.com \
            --quiet
